{% set name = "pytest-httpx" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_httpx-{{ version }}.tar.gz
  sha256: 703433f65951bde6e08d4b1d8956f8f9dec4b3046c2805414e40adb87908ee7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpx ==0.18.*
    - pytest ==6.*
    - python >=3.6

test:
  imports:
    - pytest_httpx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colin-b.github.io/pytest_httpx/
  summary: Send responses to httpx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
