{% set name = "pytest-httpx" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_httpx-{{ version }}.tar.gz
  sha256: bf04bb73d3702de3b03055db209bdcec7930193e96036d20565dc49ef6d435e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - httpx ==0.22.*
    - pytest ==6.*
    - python >=3.7

test:
  imports:
    - pytest_httpx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colin-b.github.io/pytest_httpx/
  summary: Send responses to httpx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
