{% set name = "pytest-httpx" %}
{% set version = "0.17.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_httpx-{{ version }}.tar.gz
  sha256: 49c3e6d4e702ce817a51826c0e95a538b8eccefb9feebc6cff6ddd099fc10946

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - httpx ==0.21.*
    - pytest ==6.*
    - python >=3.6

test:
  imports:
    - pytest_httpx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colin-b.github.io/pytest_httpx/
  summary: Send responses to httpx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
